title: CVTE - 前端代码规范
subtitle: "Front-End Coding Guidelines"
description: "Best Coding Guidelines For Front-End Developer."
author: CVTE
language: zh-cn
timezone: UTC
url: http://fe-guide.gz.cvte.cn/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: https://github.com/FE-CCY/guide.git
  branch: master

disqus_shortname:
google_analytics: 
baidu_analytics: 
fb_admins: 100000247608790
swiftype_key: 
github: chenchangyan/guide
gh:
  user: chenchangyan
  repo: guide

